// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZekterfyInfrastructure;

#nullable disable

namespace ZekterfyInfrastructure.Migrations
{
    [DbContext(typeof(DbZekterfyContext))]
    partial class DbZekterfyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZekterfyDomain.Model.Album", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("albums_pkey");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Pseudonym")
                        .HasColumnType("character varying")
                        .HasColumnName("pseudonym");

                    b.Property<DateOnly>("birthdate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("authors_pkey");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.AuthorAlbum", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("AuthorId");

                    b.ToTable("author_albums", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.AuthorGenre", b =>
                {
                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("author_genres", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Added")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("favorites_pkey");

                    b.HasIndex("SongId");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Follower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("followers_pkey");

                    b.HasIndex("AuthorId");

                    b.HasIndex("UserId");

                    b.ToTable("followers", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genres_pkey");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("PlayedAt")
                        .HasColumnType("date")
                        .HasColumnName("played_at");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserId1")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("history_pkey");

                    b.HasIndex("UserId1")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "history_user_id_index");

                    b.ToTable("history", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("queue_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("queue", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("reason");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("reports_pkey");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Song", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<int>("Lenght")
                        .HasColumnType("integer")
                        .HasColumnName("lenght");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int?>("NumOfStreams")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_streams");

                    b.HasKey("Id")
                        .HasName("songs_pkey");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.SongAuthor", b =>
                {
                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SongId");

                    b.ToTable("song_authors", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.SongGenre", b =>
                {
                    b.Property<int?>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.HasIndex("GenreId");

                    b.HasIndex("SongId");

                    b.ToTable("song_genres", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar_url");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ZekterfyDomain.Model.AuthorAlbum", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("fk_album");

                    b.HasOne("ZekterfyDomain.Model.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("fk_author");

                    b.Navigation("Album");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.AuthorGenre", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("author_id");

                    b.HasOne("ZekterfyDomain.Model.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .HasConstraintName("genre_id");

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Favorite", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Follower", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_author_id");

                    b.HasOne("ZekterfyDomain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_id");

                    b.Navigation("Author");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.History", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("history_user_id_fkey");

                    b.HasOne("ZekterfyDomain.Model.User", null)
                        .WithOne("History")
                        .HasForeignKey("ZekterfyDomain.Model.History", "UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Queue", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Report", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .HasConstraintName("fk_song");

                    b.HasOne("ZekterfyDomain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Song", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("fk_album_id");

                    b.HasOne("ZekterfyDomain.Model.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.SongAuthor", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("author_id");

                    b.HasOne("ZekterfyDomain.Model.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .HasConstraintName("song_id");

                    b.Navigation("Author");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.SongGenre", b =>
                {
                    b.HasOne("ZekterfyDomain.Model.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .HasConstraintName("genre_id");

                    b.HasOne("ZekterfyDomain.Model.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .HasConstraintName("song_id");

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("ZekterfyDomain.Model.User", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
